package org.ttn.ecommerce.entities.enums;

public enum ToStatus {
    CANCELLED,
    ORDER_CONFIRMED,
    ORDER_REJECTED,
    ORDER_SHIPPED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    CLOSED,
    DELIVERED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    PICK_UP_INITIATED,
    PICK_UP_COMPLETED
}